services:
  php:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  php-worker:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
